name: Java Gradle CI Build
trigger:
  branches:
    include:
      - refs/heads/development
      - refs/heads/feature/*
      - refs/heads/release/*
      - refs/heads/bugfix/*
      - refs/heads/hotfix/*
    exclude:
      - master
  paths:
    exclude:
      - "azure/*.yml"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

resources:
 repositories:
   - repository: fsm-akka-azure-pipelines
     type: github
     name: mehmetsalgar/fsm-akka-azure-pipelines
     endpoint: mehmetsalgar

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: InstallGrallVM
    variables:
      GRAALVM_VERSION: '22.3.1'
    steps:
      - bash: |
          curl -o GraalVM.tar.gz -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$(GRAALVM_VERSION)/graalvm-ce-java17-linux-amd64-$(GRAALVM_VERSION).tar.gz
          tar -xzf GraalVM.tar.gz
          export PATH=/tmp/graalvm-ce-java17-$(GRAALVM_VERSION)/bin:$PATH
          export JAVA_HOME=/tmp/graalvm-ce-java17-$(GRAALVM_VERSION)
        displayName: "Install the latest GraalVM CE 22.x for Java 17 - JDK and Native Image"
  - template: build.yml@fsm-akka-azure-pipelines
    parameters:
      sourceRepo: 'customer-relationship-adapter-application'
