name: Java Gradle CI Build
trigger:
  branches:
    include:
      - refs/heads/development
      - refs/heads/feature/*
      - refs/heads/release/*
      - refs/heads/bugfix/*
      - refs/heads/hotfix/*
    exclude:
      - master
  paths:
    exclude:
      - "azure/*.yml"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES
  


resources:
 repositories:
   - repository: fsm-akka-azure-pipelines
     type: github
     name: mehmetsalgar/fsm-akka-azure-pipelines
     endpoint: mehmetsalgar
     


stages:
- stage: Build
  displayName: Build
  jobs:
  - job: InstallGrallVM
    steps:
      - bash: |
          yum -y install graalvm22-ce-17-native-image
          export PATH="/usr/lib64/graalvm/graalvm22-ce-java17"
          export PATH=$JAVA_HOME/bin:$PATH
        displayName: "Install the latest GraalVM CE 22.x for Java 17 - JDK and Native Image"
  - template: build.yml@fsm-akka-azure-pipelines
    parameters:
      sourceRepo: 'customer-relationship-adapter-application'
